# Generated by Django 4.0.6 on 2023-05-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Critéres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critérs', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='stage',
            name='Grade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stage',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stage',
            name='prenom',
            field=models.CharField(max_length=100),
        ),
    ]
