# Generated by Django 4.0.6 on 2023-05-18 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_stage_critérs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='critérs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.critéres'),
        ),
    ]
