# Generated by Django 4.0.6 on 2023-05-18 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_stage_critérs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_de_Grille', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='critéres',
            name='nom_de_Grille',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.type'),
        ),
    ]
