# Generated by Django 4.0.6 on 2023-05-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='dossier_construction',
            field=models.FileField(default=1, upload_to='dossier/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stage',
            name='labo_de_rechercher',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stage',
            name='payes_Destiné',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stage',
            name='ville',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
