# Generated by Django 4.2.1 on 2023-06-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_stage_dossier_construction_stage_labo_de_rechercher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myfinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_field', models.DateTimeField()),
            ],
        ),
    ]
