# Generated by Django 4.2.1 on 2023-06-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_myfinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='Grade',
            field=models.CharField(choices=[('Professeur', 'Professeur'), ('MCA', 'MCA'), ('MCB', 'MCB'), ('MAA', 'MAA'), ('MAB', 'MAB'), ('doctorats régime LMD', 'doctorats régime LMD')], max_length=100),
        ),
    ]
