# Generated by Django 4.2.1 on 2023-06-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_stage_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='Grade',
            field=models.CharField(choices=[('Professeur', 'Professeur'), ('MCA', 'MCA'), ('MCB', 'MCB'), ('MAA', 'MAA'), ('MAB', 'MAB'), ('doctorats régime LMD', 'doctorats régime LMD'), ('doctorats Science', 'doctorats Science')], max_length=100),
        ),
    ]
